name: {{ product_module_key }}
description: {{ product_module_name }}

version: 1.0.1

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  ez_validator: ^0.3.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

